# Generated by Django 2.0.5 on 2018-07-13 02:37

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='english_name',
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True, verbose_name='论文署名'),
        ),
    ]
