# Generated by Django 2.0.5 on 2018-07-14 17:36

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180713_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', jsonfield.fields.JSONField()),
            ],
        ),
    ]
