# Generated by Django 2.0.5 on 2018-07-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180715_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='english_name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='论文署名一'),
        ),
        migrations.AlterField(
            model_name='user',
            name='english_name2',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='论文署名二'),
        ),
        migrations.AlterField(
            model_name='user',
            name='english_name3',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='论文署名三'),
        ),
        migrations.AlterField(
            model_name='user',
            name='english_name4',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='论文署名四'),
        ),
    ]
