# Generated by Django 2.0.5 on 2018-05-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chinese_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='中文名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=20, verbose_name='所在院系名称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='english_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='论文署名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='工号'),
        ),
    ]
