# Generated by Django 2.0.5 on 2018-07-15 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180715_0916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
