# Generated by Django 2.0.5 on 2018-07-12 13:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180528_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='english_name',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
