# Generated by Django 2.0.5 on 2018-07-12 15:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180712_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='english_name',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
